# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SlackTeam' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SlackTeam
  pod 'Alamofire', '~> 3.5.0'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'RealmSwift'

end
